### PR TITLE
Tool integration - Standard.JS

### LINKED ISSUE #55: Integrate Standard JS
Estimated effort: medium
Acceptance Criteria: Integrate static tool standard js and make sure that it runs

### PR DESCRIPTION
**Pull request by philliparaujo**
### Local installation (Part 1)
Created new branch and ran `npm install standard --save-dev`.
Ran standard tool on entire directory using `npx standard`.

#### Proof
Project 3A installation 1

First screenshot shows the StandardJS tool being locally installed.

Project 3A installation 2

The second screenshot shows that I ran npx standard and put the outputs of the command into a file. Running `wc -l` on the two files shows the number of lines they have.

### Artifacts
The output of running `npx standard` was redirected to `standard.out`, but since the output was so big (~250K lines), I sampled the first 10,000 lines in `standard-short.out`, which can be viewed on GitHub by clicking "View file". The first 10 lines of the output look like:
```
/home/phillip/NodeBB-group/Gruntfile.js:1:13: Extra semicolon. (semi)
/home/phillip/NodeBB-group/Gruntfile.js:3:29: Extra semicolon. (semi)
/home/phillip/NodeBB-group/Gruntfile.js:4:31: Extra semicolon. (semi)
/home/phillip/NodeBB-group/Gruntfile.js:7:1: Unexpected tab character. (no-tabs)
/home/phillip/NodeBB-group/Gruntfile.js:7:1: Expected indentation of 2 spaces but found 1 tab. (indent)
/home/phillip/NodeBB-group/Gruntfile.js:7:17: Unexpected trailing comma. (comma-dangle)
/home/phillip/NodeBB-group/Gruntfile.js:8:3: Extra semicolon. (semi)
/home/phillip/NodeBB-group/Gruntfile.js:9:35: Extra semicolon. (semi)
/home/phillip/NodeBB-group/Gruntfile.js:10:42: Extra semicolon. (semi)
/home/phillip/NodeBB-group/Gruntfile.js:12:24: Extra semicolon. (semi)
```
The file path `/home/phillip/NodeBB-group` is my where I store the local repo for our group. Even though these first few lines only show one file, the outfile has formatting suggestions for many other files, including ones that we edited.

### Tool Integration (Part 2)
I added a Github Actions to pushes that triggers StandardJS on a git push or a pull request. 

### NOTE
**Unfortunately, StandardJS formatting is not compatible with eslint formatting. I modified `public/src/modules/chat.js` to pass when running `npx standard`, but essentially all other files will fail. Because of this change though, the `eslint`er fails on that same file. I modified the `standard.out` file to show what running `npx standard` looked like before making formatting changes.**

Resolves #55

### CODE REVIEW

**Review by KesterTan — CHANGES_REQUESTED** [review]
Should we also have the new package.json with standard-js?

**Comment by philliparaujo** [comment]
> Should we also have the new package.json with standard-js?

Yes but I believe the package.json is git ignored, so if I add standard to the file it won't be saved when I commit it. I asked in class and the professor said screenshots work as installation, at least for now.

**Review by heyanuja — COMMENTED** [review]
Looks good to me, will assess further when looking to merge

**Review by katcday — APPROVED** [review]
Looks good to me! Make sure to include why signals aren't passing.

**Review by KesterTan — APPROVED** [review]
LGTM other than the lint/build checks

**Pull request merged**
